# Generated by Django 4.1.3 on 2022-11-24 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'CallStatus',
                'verbose_name_plural': 'CallStatus',
                'db_table': 'callStatus',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.TextField()),
                ('photo', models.FileField(upload_to='')),
                ('birthdate', models.DateField()),
                ('cv', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='DenialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'DenialStatus',
                'verbose_name_plural': 'DenialStatus',
                'db_table': 'denialStatus',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('salary', models.IntegerField()),
                ('expirence', models.IntegerField()),
                ('employment', models.TextField()),
                ('definition', models.TextField()),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='MeetEmpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'MeetEmpStatus',
                'verbose_name_plural': 'MeetEmpStatus',
                'db_table': 'meetEmpStatus',
            },
        ),
        migrations.CreateModel(
            name='MeetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'MeetStatus',
                'verbose_name_plural': 'MeetStatus',
                'db_table': 'meetStatus',
            },
        ),
        migrations.CreateModel(
            name='StatusJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'StatusJob',
                'verbose_name_plural': 'StatusJob',
                'db_table': 'statusjob',
            },
        ),
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'TestStatus',
                'verbose_name_plural': 'TestStatus',
                'db_table': 'testStatus',
            },
        ),
        migrations.CreateModel(
            name='JobSeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.IntegerField()),
                ('offer_definition', models.TextField()),
                ('release_date', models.DateField()),
                ('callStatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.callstatus')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.job')),
                ('meet_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.meetstatus')),
                ('meetemp_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.meetempstatus')),
                ('test_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.teststatus')),
            ],
            options={
                'verbose_name': 'JobSeek',
                'verbose_name_plural': 'JobSeek',
                'db_table': 'jobseek',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.statusjob'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.TextField()),
                ('value_before', models.TextField()),
                ('value_after', models.TextField()),
                ('data', models.DateField()),
                ('job_seek', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='start.jobseek')),
            ],
            options={
                'verbose_name': 'ActionHistory',
                'verbose_name_plural': 'ActionHistory',
                'db_table': 'actionHistory',
            },
        ),
    ]
