# Generated by Django 4.1.3 on 2022-11-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseek',
            name='callStatus',
        ),
        migrations.AddField(
            model_name='jobseek',
            name='call_tatus',
            field=models.ForeignKey(db_column='call_tatus', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='start.callstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='job_seek',
            field=models.ForeignKey(db_column='job_seek', on_delete=django.db.models.deletion.DO_NOTHING, to='start.jobseek'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id_status',
            field=models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.DO_NOTHING, to='start.statusjob'),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='candidate',
            field=models.ForeignKey(db_column='candidate', on_delete=django.db.models.deletion.DO_NOTHING, to='start.candidate'),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='job',
            field=models.ForeignKey(db_column='job', on_delete=django.db.models.deletion.DO_NOTHING, to='start.job'),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='meet_status',
            field=models.ForeignKey(db_column='meet_status', on_delete=django.db.models.deletion.DO_NOTHING, to='start.meetstatus'),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='meetemp_status',
            field=models.ForeignKey(db_column='meetemp_status', on_delete=django.db.models.deletion.DO_NOTHING, to='start.meetempstatus'),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='test_status',
            field=models.ForeignKey(db_column='test_status', on_delete=django.db.models.deletion.DO_NOTHING, to='start.teststatus'),
        ),
    ]
