# Generated by Django 4.1.3 on 2022-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_alter_statusjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callstatus',
            name='status',
            field=models.CharField(choices=[('Состоялось', 'Состоялось'), ('Перезвонить', 'Перезвонить'), ('Недозвон', 'Недозвон')], max_length=300),
        ),
        migrations.AlterField(
            model_name='denialstatus',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Отказ рекрутёра', 'Отказ рекрутёра'), ('Отказ соискателя', 'Отказ соискателя'), ('Отказ заказчика', 'Отказ заказчика')], max_length=300),
        ),
        migrations.AlterField(
            model_name='meetempstatus',
            name='status',
            field=models.CharField(choices=[('Состоялось', 'Состоялось'), ('Перезвонить', 'Перезвонить'), ('Недозвон', 'Недозвон')], max_length=300),
        ),
        migrations.AlterField(
            model_name='meetstatus',
            name='status',
            field=models.CharField(choices=[('Запланировано', 'Запланировано'), ('Состоялось', 'Состоялось'), ('Не состоялось', 'Не состоялось')], max_length=300),
        ),
        migrations.AlterField(
            model_name='teststatus',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Не выполнено', 'Не выполнено'), ('Отказ от выполнения', 'Отказ от выполнения'), ('Выполнено', 'Выполнено')], max_length=300),
        ),
    ]
