# Generated by Django 4.1.3 on 2022-11-25 14:47

from django.db import migrations, models
import start.models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_alter_callstatus_status_alter_denialstatus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='definition',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to=start.models.userCV_directory_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(upload_to=start.models.userPhoto_directory_path),
        ),
    ]
