# Generated by Django 4.1.3 on 2022-11-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_job_definition_alter_candidate_cv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseek',
            old_name='call_tatus',
            new_name='call_status',
        ),
        migrations.RenameField(
            model_name='jobseek',
            old_name='call_tatus_defenition',
            new_name='call_status_defenition',
        ),
    ]
