# Generated by Django 4.1.3 on 2022-11-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_rename_call_tatus_jobseek_call_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseek',
            name='denial_status',
            field=models.ForeignKey(db_column='denial_status', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='start.denialstatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='definition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='call_status',
            field=models.ForeignKey(db_column='call_status', on_delete=django.db.models.deletion.DO_NOTHING, to='start.callstatus'),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='call_status_defenition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='meet_status_defenition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='meetemp_status_defenition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseek',
            name='test_status_defenition',
            field=models.TextField(null=True),
        ),
    ]
